# Generated by Django 2.0.7 on 2018-07-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its_eCommerce', '0002_auto_20180727_1136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tshirt',
            new_name='Specs',
        ),
        migrations.RenameModel(
            old_name='Fruit',
            new_name='Watch',
        ),
        migrations.DeleteModel(
            name='Cup',
        ),
        migrations.DeleteModel(
            name='Shoe',
        ),
    ]
