# Generated by Django 2.1 on 2018-08-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its_eCommerce', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
