# Generated by Django 2.1 on 2018-08-30 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its_eCommerce', '0008_wish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='paid',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='total',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='user',
        ),
    ]
