# Generated by Django 2.1 on 2018-08-31 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its_eCommerce', '0010_auto_20180830_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='product',
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
