# Generated by Django 2.0.7 on 2018-12-07 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its_eCommerce', '0011_auto_20180830_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth',
        ),
    ]
